//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::post_tags::Entity as PostTags;
pub use super::posts::Entity as Posts;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
