//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    poem_openapi :: Enum,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "posts_status_enum")]
pub enum PostsStatusEnum {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "archived")]
    Archived,
    #[sea_orm(string_value = "removed")]
    Removed,
}
