# GitHub Actions workflow for testing Docker builds on pull requests

name: Test Docker Builds

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'container/**'
      - 'src/**'
      - 'entities/**'
      - 'migration/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/**'

jobs:
  test-builds:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - name: posts-service
            dockerfile: container/Containerfile
          - name: entities
            dockerfile: container/Containerfile.entities
          - name: migration
            dockerfile: container/Containerfile.migration

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test build ${{ matrix.name }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-summary:
    runs-on: ubuntu-latest
    needs: test-builds
    if: always()
    steps:
      - name: Check build results
        run: |
          if [[ "${{ needs.test-builds.result }}" == "success" ]]; then
            echo "✅ All Docker builds completed successfully"
          else
            echo "❌ One or more Docker builds failed"
            exit 1
          fi
