# GitHub Actions workflow for building and publishing Docker image to GitHub Container Registry
# Save this file as .github/workflows/docker-publish.yml

name: Build and Publish Docker image

on:
  push:
    branches: [ main ]
    tags:
      - '*'  # triggers on any tag
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "::set-output name=tag::latest"
          else
            echo "::set-output name=tag::nightly"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: container/Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
